=== hugomelendez/tesis-jpf-2006/trunk/tesis-javapathfinder-sincambiosTypeState/src/tesis/templates/ProblemDefinition.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ProblemDefinition" type="definitiontype" />
	<xs:complexType name="definitiontype">
		<xs:sequence>
			<xs:element name="events" type="eventlisttype" />
			<xs:element name="eventsObservables" type="labeleventlisttype" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="eventlisttype">
		<xs:sequence>
			<xs:element name="event" type="eventtype" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="labeleventlisttype">
		<xs:sequence>
			<xs:element name="event" type="labeleventtype" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="eventtype">
        <xs:sequence>
			<xs:element name="label" type="xs:string" />
			<xs:element name="instruction" type="instructiontype" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="labeleventtype">
        <xs:sequence>
			<xs:element name="label" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="instructiontype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="invoke" />
			<xs:enumeration value="return" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== hugomelendez/tesis-jpf-2006/trunk/tesis-javapathfinder/src/tesis/CasoDeEstudio_simple/propiedad5/Events.xml
<?xml version="1.0" ?>
<ProblemDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ProblemDefinition.xsd">
	<events>
	    <event type="invoke" name="runPersona" label="runPersona" />
	    <event type="invoke" name="runAscensor" label="runAscensor" />
	    <event type="invoke" name="runControlador" label="runControlador" />

	    <event type="invoke" name="subir" label="subir" />
	    <event type="invoke" name="bajar" label="bajar" />
	    <event type="invoke" name="continuarSubir" label="continuarSubir" />
	    <event type="invoke" name="continuarBajar" label="continuarBajar" />

		<!-- para quedar fuera del ctx -->
	    <event type="invoke" name="terminoPersona" label="terminoPersona" />

	    <event type="invoke" name="solicitudAscensorPiso4" label="solicitudAscensorPiso4" />
	    <event type="invoke" name="atenderSolicitudPiso4" label="atenderSolicitudPiso4" />
	</events>
</ProblemDefinition>

=== hugomelendez/tesis-jpf-2006/tesis-javapathfinder-sincambiosTypeState/src/tesis/Ejemplo_PC/Events.xml
<?xml version="1.0" ?>
<ProblemDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ProblemDefinition.xsd">
	<events>
	    <event type="invoke" name="abrirPuertas" label="AP" />
	    <event type="invoke" name="cerrarPuertas" label="CP" />
	    <event type="invoke" name="pasarPor" label="PP" />
	    <event type="invoke" name="subir" label="S" />
	    <event type="invoke" name="bajar" label="B" />
	    <event type="invoke" name="irA" label="IA" />
	    <event type="invoke" name="arrancar" label="A" />
	    <event type="invoke" name="atenderSolicitud" label="AS" />
	    <event type="invoke" name="esperar" label="E" />
	    <event type="invoke" name="apretarBoton" label="AB" />
	</events>
</ProblemDefinition>

=== hugomelendez/tesis-jpf-2006/tesis-javapathfinder-sincambiosTypeState/src/tesis/CasoDeEstudio_simple/propiedad2/Events.xml
<?xml version="1.0" ?>
<ProblemDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ProblemDefinition.xsd">
	<events>
	    <event type="invoke" name="runPersona" label="runPersona" />
	    <event type="invoke" name="runAscensor" label="runAscensor" />
	    <event type="invoke" name="runControlador" label="runControlador" />
	    <event type="invoke" name="abrirPuertas" label="abrirPuertas" />
	    <event type="invoke" name="estoyEn" label="estoyEn" />
	    <event type="invoke" name="saliDePiso" label="saliDePiso" />
	    <event type="invoke" name="terminoPersona" label="terminoPersona" />
	</events>
</ProblemDefinition>

=== hugomelendez/tesis-jpf-2006/tesis-javapathfinder/src/tesis/CasoDeEstudio_simple/Events.xml
<?xml version="1.0" ?>
<ProblemDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ProblemDefinition.xsd">
	<events>
	    <event type="invoke" name="runPersona" label="runPersona" />
	    <event type="invoke" name="runAscensor" label="runAscensor" />
	    <event type="invoke" name="runControlador" label="runControlador" />
	    <event type="invoke" name="abrirPuertas" label="abrirPuertas" />
	    <event type="invoke" name="cerrarPuertas" label="cerrarPuertas" />
	    <event type="invoke" name="subir" label="subir" />
	    <event type="invoke" name="bajar" label="bajar" />
	    <event type="invoke" name="terminoPersona" label="terminoPersona" />
	    <event type="invoke" name="detenerse" label="detenerse" />
	    
	    
	</events>
</ProblemDefinition>
